name: Frontend CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse
        run: npm run lighthouse

      - name: Extract Lighthouse score
        id: lighthouse_score
        run: echo "::set-output name=score::$(cat lighthouse-report.json | jq -r '.categories.performance.score')"

  bonus_points:
    runs-on: ubuntu-latest
    steps:
      - name: Add bonus points based on Lighthouse score
        if: steps.lighthouse.outputs.score >= 0.9
        run: echo "Bonus points: 3"
